import React from 'react';

const AlgoStreakPrivacy = () => {
  return (
    <div style={styles.pageContainer}>
      <div style={styles.content}>
        <h1 style={styles.title}>Privacy Policy</h1>
        <p style={styles.lastUpdated}>Last updated: June 06, 2026</p>

        <p style={styles.paragraph}>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p style={styles.paragraph}>
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 style={styles.heading}>Interpretation and Definitions</h2>
        
        <h3 style={styles.subHeading}>Interpretation</h3>
        <p style={styles.paragraph}>
          The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 style={styles.subHeading}>Definitions</h3>
        <p style={styles.paragraph}>For the purposes of this Privacy Policy:</p>
        <ul style={styles.list}>
          <li style={styles.listItem}><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li style={styles.listItem}><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li style={styles.listItem}><strong>Application</strong> refers to AlgoStreak, the software program provided by the Company.</li>
          <li style={styles.listItem}><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to AlgoStreak.</li>
          <li style={styles.listItem}><strong>Country</strong> refers to: Bihar, India.</li>
          <li style={styles.listItem}><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li style={styles.listItem}><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>
          <li style={styles.listItem}><strong>Service</strong> refers to the Application.</li>
          <li style={styles.listItem}><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
          <li style={styles.listItem}><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li style={styles.listItem}><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 style={styles.heading}>Collecting and Using Your Personal Data</h2>
        
        <h3 style={styles.subHeading}>Types of Data Collected</h3>
        
        <h4 style={styles.minorHeading}>Personal Data</h4>
        <p style={styles.paragraph}>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul style={styles.list}>
          <li style={styles.listItem}>Email address</li>
          <li style={styles.listItem}>First name and last name</li>
        </ul>

        <h4 style={styles.minorHeading}>Usage Data</h4>
        <p style={styles.paragraph}>Usage Data is collected automatically when using the Service.</p>
        <p style={styles.paragraph}>
          Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>

        <h3 style={styles.subHeading}>Use of Your Personal Data</h3>
        <p style={styles.paragraph}>The Company may use Personal Data for the following purposes:</p>
        <ul style={styles.list}>
          <li style={styles.listItem}><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li style={styles.listItem}><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
          <li style={styles.listItem}><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
          <li style={styles.listItem}><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, and determining the effectiveness of our promotional campaigns.</li>
        </ul>

        <h3 style={styles.subHeading}>Retention of Your Personal Data</h3>
        <p style={styles.paragraph}>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
        </p>

        <h3 style={styles.subHeading}>Transfer of Your Personal Data</h3>
        <p style={styles.paragraph}>
          Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
        </p>

        <h3 style={styles.subHeading}>Delete Your Personal Data</h3>
        <p style={styles.paragraph}>
          You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.
        </p>

        <h3 style={styles.subHeading}>Disclosure of Your Personal Data</h3>
        <ul style={styles.list}>
          <li style={styles.listItem}><strong>Business Transactions:</strong> If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</li>
          <li style={styles.listItem}><strong>Law enforcement:</strong> Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
        </ul>

        <h3 style={styles.subHeading}>Security of Your Personal Data</h3>
        <p style={styles.paragraph}>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </p>

        <h2 style={styles.heading}>Children's Privacy</h2>
        <p style={styles.paragraph}>
          Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
        </p>

        <h2 style={styles.heading}>Links to Other Websites</h2>
        <p style={styles.paragraph}>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
        </p>

        <h2 style={styles.heading}>Changes to this Privacy Policy</h2>
        <p style={styles.paragraph}>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
        </p>

        <h2 style={styles.heading}>Contact Us</h2>
        <p style={styles.paragraph}>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul style={styles.list}>
          <li style={styles.listItem}>By email: <strong>raunakranjann@gmail.com</strong></li>
        </ul>

        <div style={styles.footer}>
          <a href="/" style={styles.textLink}>&larr; Return to Home</a>
        </div>
      </div>
    </div>
  );
};

// --- STYLES ---
const styles = {
  pageContainer: {
    minHeight: '100vh',
    display: 'flex',
    justifyContent: 'center',
    backgroundColor: '#F8F9FA',
    padding: '40px 20px',
    fontFamily: 'sans-serif',
    color: '#333'
  },
  content: {
    backgroundColor: '#FFFFFF',
    maxWidth: '800px',
    width: '100%',
    borderRadius: '16px',
    padding: '40px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.05)',
  },
  title: {
    margin: '0 0 10px 0',
    color: '#202124',
    fontSize: '32px'
  },
  lastUpdated: {
    color: '#9AA0A6',
    fontSize: '14px',
    marginBottom: '32px'
  },
  heading: {
    color: '#202124',
    fontSize: '24px',
    marginTop: '32px',
    marginBottom: '12px',
    borderBottom: '2px solid #FFF3E0',
    paddingBottom: '8px',
    display: 'inline-block'
  },
  subHeading: {
    color: '#202124',
    fontSize: '18px',
    marginTop: '24px',
    marginBottom: '8px',
  },
  minorHeading: {
    color: '#5F6368',
    fontSize: '16px',
    marginTop: '16px',
    marginBottom: '8px',
  },
  paragraph: {
    color: '#5F6368',
    fontSize: '16px',
    lineHeight: '1.6',
    marginBottom: '16px'
  },
  list: {
    marginBottom: '24px',
    paddingLeft: '24px'
  },
  listItem: {
    color: '#5F6368',
    fontSize: '16px',
    lineHeight: '1.6',
    marginBottom: '8px'
  },
  footer: {
    marginTop: '40px',
    paddingTop: '20px',
    borderTop: '1px solid #E8EAED'
  },
  textLink: {
    color: '#E65100',
    textDecoration: 'none',
    fontWeight: 'bold'
  }
};

export default AlgoStreakPrivacy;